#ExpectedExceptions.xml
expectedConditions.testsErrors.ExpectedExceptions.xml.1_Expected_exception_test=
expectedConditions.testsErrors.ExpectedExceptions.xml.2_Expected_exception_with_full_name_test=
expectedConditions.testsErrors.ExpectedExceptions.xml.3_Expected_exception_test_[wrong_exception]=Test expected exception .lang.NullPointerException, but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException was thrown
expectedConditions.testsErrors.ExpectedExceptions.xml.4_Expected_exception_test_[negative]=Test expected exception FrameworkException, but no exception was thrown in test execution
expectedConditions.testsErrors.ExpectedExceptions.xml.5_Expected_message_test=
expectedConditions.testsErrors.ExpectedExceptions.xml.6_Expected_message_test_[negative]=Test expected exception with message "some message", but no exception was thrown in test execution
expectedConditions.testsErrors.ExpectedExceptions.xml.7_Expected_result_test=
expectedConditions.testsErrors.ExpectedExceptions.xml.8_Expected_result_test_[negative]=Test result was SUCCESS, but test expected FAIL result!
expectedConditions.testsErrors.ExpectedExceptions.xml.9_Expected_result_on_specified_element_without_expected_result_for_test_[negative]=Test result was success, but fail expected on element with ref="fail1"
expectedConditions.testsErrors.ExpectedExceptions.xml.10_Expected_result_on_non_element_without_ref_[negative]=Test result was fail, this fail expected on element with ref="fail1", but was on element with ref = "null"
expectedConditions.testsErrors.ExpectedExceptions.xml.11_Expected_error_on_concrete_correct_element=
expectedConditions.testsErrors.ExpectedExceptions.xml.12_Expected_result_on_non_expected_element_[negative]=Test result was fail, this fail expected on element with ref="fail1", but was on element with ref = "fail2"
expectedConditions.testsErrors.ExpectedExceptions.xml.13_Expected_non_expected_result_on_non_expected_element_[negative]=Test result was fail, this fail expected on element with ref="fail1", but was on element with ref = "fail2"
expectedConditions.testsErrors.ExpectedExceptions.xml.14_Expected_conrete_result_on_concrete_element=
expectedConditions.testsErrors.ExpectedExceptions.xml.15_Expected_expected_expectedException=
expectedConditions.testsErrors.ExpectedExceptions.xml.16_Expected_expected_expectedMessage=
expectedConditions.testsErrors.ExpectedExceptions.xml.17_Expected_expected_expectedException_expectedMessage=
expectedConditions.testsErrors.ExpectedExceptions.xml.18_Expected_expected_where_expectedException_expectedMessage=

#CombinedExpectedConditions.xml
expectedConditions.testsErrors.CombinedExpectedConditions.xml.1_Expected_message_[negative]=Test expected exception with message "wrong message", but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException with message "Unknown action [nonExistsAction] for element Webelement" was thrown
expectedConditions.testsErrors.CombinedExpectedConditions.xml.2_Expected_expected_expectedException=
expectedConditions.testsErrors.CombinedExpectedConditions.xml.3_Expected_expected_success_expectedException_[negative]=Test result was ERROR, but test expected SUCCESS result!
expectedConditions.testsErrors.CombinedExpectedConditions.xml.4_Expected_expected_expectedMessage=
expectedConditions.testsErrors.CombinedExpectedConditions.xml.5_Expected_expected_expectedException_expectedMessage=
expectedConditions.testsErrors.CombinedExpectedConditions.xml.6_Expected_expected_where_expectedException_expectedMessage=
expectedConditions.testsErrors.CombinedExpectedConditions.xml.7_Expected_expected_success_where_expectedException_expectedMessage_[negative]=Test result was ERROR, but test expected SUCCESS result!
expectedConditions.testsErrors.CombinedExpectedConditions.xml.8_Expected_expected_expectedException_[negative]=Test expected exception FrameworkException111, but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException was thrown
expectedConditions.testsErrors.CombinedExpectedConditions.xml.9_Expected_expected_expectedMessage_[negative]=Test expected exception with message "wrong message", but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException with message "Unknown action [nonExistsAction] for element Webelement" was thrown
expectedConditions.testsErrors.CombinedExpectedConditions.xml.10_Expected_expected_expectedException_expectedMessage_[negative]=Test expected exception wrong exception, but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException was thrown\nTest expected exception with message "wrong message", but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException with message "Unknown action [nonExistsAction] for element Webelement" was thrown
expectedConditions.testsErrors.CombinedExpectedConditions.xml.11_Expected_expected_where_expectedException_expectedMessage_[negative]=Test result was fail, this fail expected on element with ref="fail222", but was on element with ref = "fail1"\nTest expected exception with message "wrong message", but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException with message "Unknown action [nonExistsAction] for element Webelement" was thrown
expectedConditions.testsErrors.CombinedExpectedConditions.xml.12_Expected_expected_success_where[wrong_element]_expectedException_expectedMessage_[negative]=Test result was fail, this fail expected on element with ref="fail222", but was on element with ref = "fail1"\nTest result was ERROR, but test expected SUCCESS result!\nTest expected exception with message "wrong message", but another exception org.jazzteam.xml2selenium.core.exceptions.FrameworkException with message "Unknown action [nonExistsAction] for element Webelement" was thrown
expectedConditions.testsErrors.CombinedExpectedConditions.xml.13_Expected_where_success_expectedException=Test result was ERROR, but test expected SUCCESS result!